<?php
/**
 * Countries and shipping
 *
 * Returns an array of countries and codes and shipping.
 */

defined( 'ABSPATH' ) || exit;

return array(
	'AF' => array(
        'name' => __( 'Afghanistan', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ),
    'AX' => array(
        'name' => __( 'Åland Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'AL' => array(
        'name' => __( 'Albania', 'woocommerce' ),
        'first_weight'  => 217,
        'weight_ratio'  => 5000,
        'continued_weight'   => 39,
    ), 
    'DZ' => array(
        'name' => __( 'Algeria', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'AS' => array(
        'name' => __( 'American Samoa', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'AD' => array(
        'name' => __( 'Andorra', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 48,
    ), 
    'AO' => array(
        'name' => __( 'Angola', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'AI' => array(
        'name' => __( 'Anguilla', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'AQ' => array(
        'name' => __( 'Antarctica', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'AG' => array(
        'name' => __( 'Antigua and Barbuda', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'AR' => array(
        'name' => __( 'Argentina', 'woocommerce' ),
        'first_weight'  => 235,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'AM' => array(
        'name' => __( 'Armenia', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'AW' => array(
        'name' => __( 'Aruba', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'AU' => array(
        'name' => __( 'Australia', 'woocommerce' ),
        'first_weight'  => 85.5,
        'weight_ratio'  => 5000,
        'continued_weight'   => 28.68,
    ), 
    'AT' => array(
        'name' => __( 'Austria', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'AZ' => array(
        'name' => __( 'Azerbaijan', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'BS' => array(
        'name' => __( 'Bahamas', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'BH' => array(
        'name' => __( 'Bahrain', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 55,
    ), 
    'BD' => array(
        'name' => __( 'Bangladesh', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'BB' => array(
        'name' => __( 'Barbados', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'BY' => array(
        'name' => __( 'Belarus', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'BE' => array(
        'name' => __( 'Belgium', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'PW' => array(
        'name' => __( 'Belau', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'BZ' => array(
        'name' => __( 'Belize', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'BJ' => array(
        'name' => __( 'Benin', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'BM' => array(
        'name' => __( 'Bermuda', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'BT' => array(
        'name' => __( 'Bhutan', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'BO' => array(
        'name' => __( 'Bolivia', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'BQ' => array(
        'name' => __( 'Bonaire, Saint Eustatius and Saba', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'BA' => array(
        'name' => __( 'Bosnia and Herzegovina', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'BW' => array(
        'name' => __( 'Botswana', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'BV' => array(
        'name' => __( 'Bouvet Island', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'BR' => array(
        'name' => __( 'Brazil', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'IO' => array(
        'name' => __( 'British Indian Ocean Territory', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'BN' => array(
        'name' => __( 'Brunei', 'woocommerce' ),
        'first_weight'  => 111,
        'weight_ratio'  => 5000,
        'continued_weight'   => 26,
    ), 
    'BG' => array(
        'name' => __( 'Bulgaria', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'BF' => array(
        'name' => __( 'Burkina Faso', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'BI' => array(
        'name' => __( 'Burundi', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'KH' => array(
        'name' => __( 'Cambodia', 'woocommerce' ),
        'first_weight'  => 145,
        'weight_ratio'  => 5000,
        'continued_weight'   => 47,
    ), 
    'CM' => array(
        'name' => __( 'Cameroon', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'CA' => array(
        'name' => __( 'Canada', 'woocommerce' ),
        'first_weight'  => 168,
        'weight_ratio'  => 5000,
        'continued_weight'   => 40,
    ), 
    'CV' => array(
        'name' => __( 'Cape Verde', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'KY' => array(
        'name' => __( 'Cayman Islands', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'CF' => array(
        'name' => __( 'Central African Republic', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'TD' => array(
        'name' => __( 'Chad', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'CL' => array(
        'name' => __( 'Chile', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 75,
    ), 
    'CN' => array(
        'name' => __( 'China', 'woocommerce' ),
        'first_weight'  => 22,
        'weight_ratio'  => 5000,
        'continued_weight'   => 8,
    ), 
    'CX' => array(
        'name' => __( 'Christmas Island', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'CC' => array(
        'name' => __( 'Cocos (Keeling) Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'CO' => array(
        'name' => __( 'Colombia', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'KM' => array(
        'name' => __( 'Comoros', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'CG' => array(
        'name' => __( 'Congo (Brazzaville)', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'CD' => array(
        'name' => __( 'Congo (Kinshasa)', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'CK' => array(
        'name' => __( 'Cook Islands', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'CR' => array(
        'name' => __( 'Costa Rica', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 75,
    ), 
    'HR' => array(
        'name' => __( 'Croatia', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'CU' => array(
        'name' => __( 'Cuba', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'CW' => array(
        'name' => __( 'Cura&ccedil;ao', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'CY' => array(
        'name' => __( 'Cyprus', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'CZ' => array(
        'name' => __( 'Czech Republic', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'DK' => array(
        'name' => __( 'Denmark', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'DJ' => array(
        'name' => __( 'Djibouti', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'DM' => array(
        'name' => __( 'Dominica', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 75,
    ), 
    'DO' => array(
        'name' => __( 'Dominican Republic', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 75,
    ), 
    'EC' => array(
        'name' => __( 'Ecuador', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'EG' => array(
        'name' => __( 'Egypt', 'woocommerce' ),
        'first_weight'  => 117.44,
        'weight_ratio'  => 5000,
        'continued_weight'   => 40.64,
    ), 
    'SV' => array(
        'name' => __( 'El Salvador', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'GQ' => array(
        'name' => __( 'Equatorial Guinea', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'ER' => array(
        'name' => __( 'Eritrea', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'EE' => array(
        'name' => __( 'Estonia', 'woocommerce' ),
        'first_weight'  => 147,
        'weight_ratio'  => 5000,
        'continued_weight'   => 29,
    ), 
    'ET' => array(
        'name' => __( 'Ethiopia', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'FK' => array(
        'name' => __( 'Falkland Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'FO' => array(
        'name' => __( 'Faroe Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'FJ' => array(
        'name' => __( 'Fiji', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'FI' => array(
        'name' => __( 'Finland', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'FR' => array(
        'name' => __( 'France', 'woocommerce' ),
        'first_weight'  => 141.44,
        'weight_ratio'  => 5000,
        'continued_weight'   => 50.24,
    ), 
    'GF' => array(
        'name' => __( 'French Guiana', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'PF' => array(
        'name' => __( 'French Polynesia', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'TF' => array(
        'name' => __( 'French Southern Territories', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'GA' => array(
        'name' => __( 'Gabon', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'GM' => array(
        'name' => __( 'Gambia', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'GE' => array(
        'name' => __( 'Georgia', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'DE' => array(
        'name' => __( 'Germany', 'woocommerce' ),
        'first_weight'  => 152.16,
        'weight_ratio'  => 5000,
        'continued_weight'   => 49.6,
    ), 
    'GH' => array(
        'name' => __( 'Ghana', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'GI' => array(
        'name' => __( 'Gibraltar', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 48,
    ), 
    'GR' => array(
        'name' => __( 'Greece', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'GL' => array(
        'name' => __( 'Greenland', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 48,
    ), 
    'GD' => array(
        'name' => __( 'Grenada', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'GP' => array(
        'name' => __( 'Guadeloupe', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'GU' => array(
        'name' => __( 'Guam', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'GT' => array(
        'name' => __( 'Guatemala', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'GG' => array(
        'name' => __( 'Guernsey', 'woocommerce' ),
        'first_weight'  => 100,
        'weight_ratio'  => 5000,
        'continued_weight'   => 30,
    ), 
    'GN' => array(
        'name' => __( 'Guinea', 'woocommerce' ),
        'first_weight'  => 280,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'GW' => array(
        'name' => __( 'Guinea-Bissau', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'GY' => array(
        'name' => __( 'Guyana', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'HT' => array(
        'name' => __( 'Haiti', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'HM' => array(
        'name' => __( 'Heard Island and McDonald Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'HN' => array(
        'name' => __( 'Honduras', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'HK' => array(
        'name' => __( 'Hong Kong', 'woocommerce' ),
        'first_weight'  => 78,
        'weight_ratio'  => 5000,
        'continued_weight'   => 10,
    ), 
    'HU' => array(
        'name' => __( 'Hungary', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'IS' => array(
        'name' => __( 'Iceland', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 48,
    ), 
    'IN' => array(
        'name' => __( 'India', 'woocommerce' ),
        'first_weight'  => 82.72,
        'weight_ratio'  => 5000,
        'continued_weight'   => 34.08,
    ), 
    'ID' => array(
        'name' => __( 'Indonesia', 'woocommerce' ),
        'first_weight'  => 145,
        'weight_ratio'  => 5000,
        'continued_weight'   => 47,
    ), 
    'IR' => array(
        'name' => __( 'Iran', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 55,
    ), 
    'IQ' => array(
        'name' => __( 'Iraq', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 55,
    ), 
    'IE' => array(
        'name' => __( 'Ireland', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'IM' => array(
        'name' => __( 'Isle of Man', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'IL' => array(
        'name' => __( 'Israel', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 55,
    ), 
    'IT' => array(
        'name' => __( 'Italy', 'woocommerce' ),
        'first_weight'  => 146.24,
        'weight_ratio'  => 5000,
        'continued_weight'   => 51.84,
    ), 
    'CI' => array(
        'name' => __( 'Ivory Coast', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'JM' => array(
        'name' => __( 'Jamaica', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'JP' => array(
        'name' => __( 'Japan', 'woocommerce' ),
        'first_weight'  => 80,
        'weight_ratio'  => 5000,
        'continued_weight'   => 19,
    ), 
    'JE' => array(
        'name' => __( 'Jersey', 'woocommerce' ),
        'first_weight'  => 100,
        'weight_ratio'  => 5000,
        'continued_weight'   => 30,
    ), 
    'JO' => array(
        'name' => __( 'Jordan', 'woocommerce' ),
        'first_weight'  => 120.64,
        'weight_ratio'  => 5000,
        'continued_weight'   => 43.84,
    ), 
    'KZ' => array(
        'name' => __( 'Kazakhstan', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'KE' => array(
        'name' => __( 'Kenya', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'KI' => array(
        'name' => __( 'Kiribati', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'KW' => array(
        'name' => __( 'Kuwait', 'woocommerce' ),
        'first_weight'  => 149,
        'weight_ratio'  => 5000,
        'continued_weight'   => 32,
    ), 
    'KG' => array(
        'name' => __( 'Kyrgyzstan', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'LA' => array(
        'name' => __( 'Laos', 'woocommerce' ),
        'first_weight'  => 145,
        'weight_ratio'  => 5000,
        'continued_weight'   => 47,
    ), 
    'LV' => array(
        'name' => __( 'Latvia', 'woocommerce' ),
        'first_weight'  => 147,
        'weight_ratio'  => 5000,
        'continued_weight'   => 29,
    ), 
    'LB' => array(
        'name' => __( 'Lebanon', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 55,
    ), 
    'LS' => array(
        'name' => __( 'Lesotho', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'LR' => array(
        'name' => __( 'Liberia', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'LY' => array(
        'name' => __( 'Libya', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'LI' => array(
        'name' => __( 'Liechtenstein', 'woocommerce' ),
        'first_weight'  => 100,
        'weight_ratio'  => 5000,
        'continued_weight'   => 30,
    ), 
    'LT' => array(
        'name' => __( 'Lithuania', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'LU' => array(
        'name' => __( 'Luxembourg', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'MO' => array(
        'name' => __( 'Macao', 'woocommerce' ),
        'first_weight'  => 90,
        'weight_ratio'  => 5000,
        'continued_weight'   => 13,
    ), 
    'MK' => array(
        'name' => __( 'North Macedonia', 'woocommerce' ),
        'first_weight'  => 373,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'MG' => array(
        'name' => __( 'Madagascar', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'MW' => array(
        'name' => __( 'Malawi', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'MY' => array(
        'name' => __( 'Malaysia', 'woocommerce' ),
        'first_weight'  => 82.4,
        'weight_ratio'  => 5000,
        'continued_weight'   => 37.44,
    ), 
    'MV' => array(
        'name' => __( 'Maldives', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'ML' => array(
        'name' => __( 'Mali', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'MT' => array(
        'name' => __( 'Malta', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 50,
    ), 
    'MH' => array(
        'name' => __( 'Marshall Islands', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'MQ' => array(
        'name' => __( 'Martinique', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'MR' => array(
        'name' => __( 'Mauritania', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'MU' => array(
        'name' => __( 'Mauritius', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'YT' => array(
        'name' => __( 'Mayotte', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'MX' => array(
        'name' => __( 'Mexico', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 40,
    ), 
    'FM' => array(
        'name' => __( 'Micronesia', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'MD' => array(
        'name' => __( 'Moldova', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'MC' => array(
        'name' => __( 'Monaco', 'woocommerce' ),
        'first_weight'  => 160,
        'weight_ratio'  => 5000,
        'continued_weight'   => 70,
    ), 
    'MN' => array(
        'name' => __( 'Mongolia', 'woocommerce' ),
        'first_weight'  => 172.92,
        'weight_ratio'  => 5000,
        'continued_weight'   => 31.99,
    ), 
    'ME' => array(
        'name' => __( 'Montenegro', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'MS' => array(
        'name' => __( 'Montserrat', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'MA' => array(
        'name' => __( 'Morocco', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'MZ' => array(
        'name' => __( 'Mozambique', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'MM' => array(
        'name' => __( 'Myanmar', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'NA' => array(
        'name' => __( 'Namibia', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'NR' => array(
        'name' => __( 'Nauru', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'NP' => array(
        'name' => __( 'Nepal', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'NL' => array(
        'name' => __( 'Netherlands', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'NC' => array(
        'name' => __( 'New Caledonia', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'NZ' => array(
        'name' => __( 'New Zealand', 'woocommerce' ),
        'first_weight'  => 145,
        'weight_ratio'  => 5000,
        'continued_weight'   => 47,
    ), 
    'NI' => array(
        'name' => __( 'Nicaragua', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'NE' => array(
        'name' => __( 'Niger', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'NG' => array(
        'name' => __( 'Nigeria', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'NU' => array(
        'name' => __( 'Niue', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'NF' => array(
        'name' => __( 'Norfolk Island', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'MP' => array(
        'name' => __( 'Northern Mariana Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'KP' => array(
        'name' => __( 'North Korea', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'NO' => array(
        'name' => __( 'Norway', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'OM' => array(
        'name' => __( 'Oman', 'woocommerce' ),
        'first_weight'  => 112.64,
        'weight_ratio'  => 5000,
        'continued_weight'   => 35.84,
    ), 
    'PK' => array(
        'name' => __( 'Pakistan', 'woocommerce' ),
        'first_weight'  => 141.44,
        'weight_ratio'  => 5000,
        'continued_weight'   => 43.84,
    ), 
    'PS' => array(
        'name' => __( 'Palestinian Territory', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'PA' => array(
        'name' => __( 'Panama', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'PG' => array(
        'name' => __( 'Papua New Guinea', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'PY' => array(
        'name' => __( 'Paraguay', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'PE' => array(
        'name' => __( 'Peru', 'woocommerce' ),
        'first_weight'  => 235,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'PH' => array(
        'name' => __( 'Philippines', 'woocommerce' ),
        'first_weight'  => 90,
        'weight_ratio'  => 5000,
        'continued_weight'   => 33,
    ), 
    'PN' => array(
        'name' => __( 'Pitcairn', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'PL' => array(
        'name' => __( 'Poland', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'PT' => array(
        'name' => __( 'Portugal', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'PR' => array(
        'name' => __( 'Puerto Rico', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'QA' => array(
        'name' => __( 'Qatar', 'woocommerce' ),
        'first_weight'  => 115.84,
        'weight_ratio'  => 5000,
        'continued_weight'   => 39.04,
    ), 
    'RE' => array(
        'name' => __( 'Reunion', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'RO' => array(
        'name' => __( 'Romania', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'RU' => array(
        'name' => __( 'Russia', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'RW' => array(
        'name' => __( 'Rwanda', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'BL' => array(
        'name' => __( 'Saint Barth&eacute;lemy', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SH' => array(
        'name' => __( 'Saint Helena', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'KN' => array(
        'name' => __( 'Saint Kitts and Nevis', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'LC' => array(
        'name' => __( 'Saint Lucia', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'MF' => array(
        'name' => __( 'Saint Martin (French part)', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SX' => array(
        'name' => __( 'Saint Martin (Dutch part)', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'PM' => array(
        'name' => __( 'Saint Pierre and Miquelon', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'VC' => array(
        'name' => __( 'Saint Vincent and the Grenadines', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SM' => array(
        'name' => __( 'San Marino', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'ST' => array(
        'name' => __( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SA' => array(
        'name' => __( 'Saudi Arabia', 'woocommerce' ),
        'first_weight'  => 125.44,
        'weight_ratio'  => 5000,
        'continued_weight'   => 40.64,
    ), 
    'SN' => array(
        'name' => __( 'Senegal', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'RS' => array(
        'name' => __( 'Serbia', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 55,
    ), 
    'SC' => array(
        'name' => __( 'Seychelles', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SL' => array(
        'name' => __( 'Sierra Leone', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SG' => array(
        'name' => __( 'Singapore', 'woocommerce' ),
        'first_weight'  => 77.12,
        'weight_ratio'  => 5000,
        'continued_weight'   => 32.16,
    ), 
    'SK' => array(
        'name' => __( 'Slovakia', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'SI' => array(
        'name' => __( 'Slovenia', 'woocommerce' ),
        'first_weight'  => 146.24,
        'weight_ratio'  => 5000,
        'continued_weight'   => 51.84,
    ), 
    'SB' => array(
        'name' => __( 'Solomon Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SO' => array(
        'name' => __( 'Somalia', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'ZA' => array(
        'name' => __( 'South Africa', 'woocommerce' ),
        'first_weight'  => 156,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'GS' => array(
        'name' => __( 'South Georgia/Sandwich Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'KR' => array(
        'name' => __( 'South Korea', 'woocommerce' ),
        'first_weight'  => 80,
        'weight_ratio'  => 5000,
        'continued_weight'   => 18,
    ), 
    'SS' => array(
        'name' => __( 'South Sudan', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'ES' => array(
        'name' => __( 'Spain', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'LK' => array(
        'name' => __( 'Sri Lanka', 'woocommerce' ),
        'first_weight'  => 125.44,
        'weight_ratio'  => 5000,
        'continued_weight'   => 43.84,
    ), 
    'SD' => array(
        'name' => __( 'Sudan', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SR' => array(
        'name' => __( 'Suriname', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SJ' => array(
        'name' => __( 'Svalbard and Jan Mayen', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'SZ' => array(
        'name' => __( 'Swaziland', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'SE' => array(
        'name' => __( 'Sweden', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'CH' => array(
        'name' => __( 'Switzerland', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'SY' => array(
        'name' => __( 'Syria', 'woocommerce' ),
        'first_weight'  => 280,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'TW' => array(
        'name' => __( 'Taiwan', 'woocommerce' ),
        'first_weight'  => 111,
        'weight_ratio'  => 5000,
        'continued_weight'   => 26,
    ), 
    'TJ' => array(
        'name' => __( 'Tajikistan', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'TZ' => array(
        'name' => __( 'Tanzania', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'TH' => array(
        'name' => __( 'Thailand', 'woocommerce' ),
        'first_weight'  => 111,
        'weight_ratio'  => 5000,
        'continued_weight'   => 26,
    ), 
    'TL' => array(
        'name' => __( 'Timor-Leste', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'TG' => array(
        'name' => __( 'Togo', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'TK' => array(
        'name' => __( 'Tokelau', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'TO' => array(
        'name' => __( 'Tonga', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'TT' => array(
        'name' => __( 'Trinidad and Tobago', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 75,
    ), 
    'TN' => array(
        'name' => __( 'Tunisia', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'TR' => array(
        'name' => __( 'Turkey', 'woocommerce' ),
        'first_weight'  => 127.04,
        'weight_ratio'  => 5000,
        'continued_weight'   => 51.84,
    ), 
    'TM' => array(
        'name' => __( 'Turkmenistan', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'TC' => array(
        'name' => __( 'Turks and Caicos Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'TV' => array(
        'name' => __( 'Tuvalu', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'UG' => array(
        'name' => __( 'Uganda', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'UA' => array(
        'name' => __( 'Ukraine', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'AE' => array(
        'name' => __( 'United Arab Emirates', 'woocommerce' ),
        'first_weight'  => 149,
        'weight_ratio'  => 5000,
        'continued_weight'   => 32,
    ), 
    'GB' => array(
        'name' => __( 'United Kingdom (UK)', 'woocommerce' ),
        'first_weight'  => 139,
        'weight_ratio'  => 5000,
        'continued_weight'   => 38,
    ), 
    'US' => array(
        'name' => __( 'United States (US)', 'woocommerce' ),
        'first_weight'  => 145,
        'weight_ratio'  => 5000,
        'continued_weight'   => 37,
    ), 
    'UM' => array(
        'name' => __( 'United States (US) Minor Outlying Islands', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'UY' => array(
        'name' => __( 'Uruguay', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'UZ' => array(
        'name' => __( 'Uzbekistan', 'woocommerce' ),
        'first_weight'  => 240,
        'weight_ratio'  => 5000,
        'continued_weight'   => 62,
    ), 
    'VU' => array(
        'name' => __( 'Vanuatu', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'VA' => array(
        'name' => __( 'Vatican', 'woocommerce' ),
        'first_weight'  => 380,
        'weight_ratio'  => 5000,
        'continued_weight'   => 120,
    ), 
    'VE' => array(
        'name' => __( 'Venezuela', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'VN' => array(
        'name' => __( 'Vietnam', 'woocommerce' ),
        'first_weight'  => 138,
        'weight_ratio'  => 5000,
        'continued_weight'   => 36,
    ), 
    'VG' => array(
        'name' => __( 'Virgin Islands (British)', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'VI' => array(
        'name' => __( 'Virgin Islands (US)', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 68,
    ), 
    'WF' => array(
        'name' => __( 'Wallis and Futuna', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'EH' => array(
        'name' => __( 'Western Sahara', 'woocommerce' ),
        'first_weight'  => 255,
        'weight_ratio'  => 5000,
        'continued_weight'   => 45,
    ), 
    'WS' => array(
        'name' => __( 'Samoa', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 65,
    ), 
    'YE' => array(
        'name' => __( 'Yemen', 'woocommerce' ),
        'first_weight'  => 200,
        'weight_ratio'  => 5000,
        'continued_weight'   => 55,
    ), 
    'ZM' => array(
        'name' => __( 'Zambia', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
    'ZW' => array(
        'name' => __( 'Zimbabwe', 'woocommerce' ),
        'first_weight'  => 220,
        'weight_ratio'  => 5000,
        'continued_weight'   => 64,
    ), 
);
